server:
  port: 8000

spring:
  application:
    name: short-link-admin
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: chen3131